name: Build Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: go-cross-build
      # You may pin to the exact commit or the version.
      # uses: thatisuday/go-cross-build@542468fed9c6be3220a6cead66abff3943e41a5d
        uses: thatisuday/go-cross-build@v1.1.0
        with:
          # Comma-separated list of "<kernel>/<arch>" combinations.
          platforms: windows/amd64,linux/amd64,Darwin/amd64,Darwin/arm64 # optional, default is linux/386,linux/amd64
          # Package (directory) in the module to build. By default, builds the module directory.
          package: module # optional, default is 
          # Compress each build file inside a ".tar.gz" archive.
          compress: true # optional, default is false
          # Binary executable filename and filenames prefix for the build files.
          name: esm # optional, default is program
          # Destination directory inside workspace to output build-artifacts.
          dest: build # optional, default is build
          # Flags to pass to the Go linker.
          ldflags: # optional, default is 
